yarnPath: .yarn/releases/yarn-stable-temp.cjs
cacheFolder: .yarn/cache
enableGlobalCache: false
nodeLinker: pnp
packageExtensions:
  "react-scripts@*":
    dependencies:
      "eslint": "^8.57.0"
      "eslint-webpack-plugin": "^3.1.1"
